src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="`post`")
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_path = 'post-default-img.png';

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="posts", cascade={"persist"})
     */
    private $tags;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PostMeta", cascade={"remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $meta;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function updateTimestamps(): void
    {
        $dateTimeNow = new \DateTime();

        $this->setUpdatedAt($dateTimeNow);

        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt($dateTimeNow);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->img_path;
    }

    public function setImgPath(string $img_path): self
    {
        $this->img_path = $img_path;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getMeta(): ?PostMeta
    {
        return $this->meta;
    }

    public function setMeta(?PostMeta $meta): self
    {
        $this->meta = $meta;

        return $this;
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Post;
use App\Entity\PostMeta;
use App\Entity\Tag;
use App\Entity\User;
use App\Form\PostType;
use App\Service\FileUploader;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/author", name="author.")
 * @IsGranted("ROLE_AUTHOR")
 */
class AuthorController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $posts = $this->getDoctrine()->getRepository(Post::class)->findBy(['author' => $this->getUser()], ['id' => 'DESC']);

        return $this->render('blog/author/index.html.twig', [
            'posts' => $posts,
        ]);
    }

    /**
     * @Route("/new", name="post_new")
     * @param Request $request
     * @param FileUploader $fileUploader
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function new(Request $request, FileUploader $fileUploader)
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        //dump($request);die;

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post_meta = new PostMeta();
            $img_file = $form->get('img_path')->getData();

            if ($img_file) {
                $filename = $fileUploader->upload($img_file);
                $post->setImgPath($filename);
            }

            $post->setAuthor($this->getUser())->setMeta($post_meta);

            $em = $this->getDoctrine()->getManager();
            $em->persist($post_meta);
            $em->persist($post);
            $em->flush();

            return $this->redirectToRoute('author.index');
        }

        return $this->render('blog/author/new.html.twig', [
            'form_post' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="post_edit")
     * @param Request $request
     * @param Post $post
     * @param FileUploader $fileUploader
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Post $post, FileUploader $fileUploader)
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $img_file = $form->get('img_path')->getData();

            if ($img_file) {
                $filesystem = new Filesystem();
                $filesystem_img = $this->getParameter('post_img');

                $file = $filesystem_img . $post->getImgPath();

                if ($filesystem->exists($file)) {
                    $filesystem->remove($file);
                }

                $filename = $fileUploader->upload($img_file);
                $post->setImgPath($filename);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('author.post_edit', ['id' => $post->getId()]);
        }

        return $this->render('blog/author/edit.html.twig', [
            'form_post' => $form->createView(),
            'post' => $post,
        ]);
    }

    /**
     * @Route("/remove/{id}", name="post_delete")
     * @param Request $request
     * @param Post $post
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function delete(Request $request, Post $post)
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return $this->redirectToRoute('author.index');
        }

        $post_entity = new Post();

        if ($post->getImgPath() !== $post_entity->getImgPath()) {
            $filesystem = new Filesystem();
            $filesystem_img = $this->getParameter('post_img');
            $file = $filesystem_img . $post->getImgPath();

            if ($filesystem->exists($file)) {
                $filesystem->remove($file);
            }
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($post);
        $em->flush();

        return $this->redirectToRoute('author.index');
    }
}

templates/blog/author/_delete_form.html.twig
<form action="{{ url('author.post_delete', {id: post.id}) }}" method="post" data-confirmation="true" id="delete-form">
    <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
    <button type="submit">
        <i class="fal fa-trash" aria-hidden="true"></i>
        <span>Remove</span>
    </button>
</form>

templates/blog/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование "{{ post.title }}"{% endblock %}

{% block body %}
    <main>
        <div class="main">
            <h1 class="main-header c-t-black">Редактирование "{{ post.title }}"</h1>
            <div class="main-container">
                <div class="container-form width-700px align-hor-center">
                    {{ form_start(form_post) }}
                    <div class="form-error">{{ form_errors(form_post.title) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.title) }}
                        <div class="form-input">{{ form_widget(form_post.title) }}</div>
                    </div>

                    <div class="form-error">{{ form_errors(form_post.content) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.content) }}
                        {{ form_widget(form_post.content) }}
                    </div>

                    <div class="form-error">{{ form_errors(form_post.category) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.category) }}
                        {{ form_widget(form_post.category) }}
                    </div>

                    <div class="form-control">
                        <div class="form-file">
                            <div class="field-file">{{ form_widget(form_post.img_path, {'attr': {'onchange': 'form_file_field(this);'}}) }}</div>
                            <label class="field-label" for="{{ form_post.img_path.vars.id }}"><i
                                        class="fal fa-upload"></i> Загрузить картинку</label>
                            <div class="field-file-name" id="form_file_name">{{ post.imgPath }}</div>
                        </div>
                    </div>

                    <div class="form-control">
                        {{ form_widget(form_post.post) }}
                    </div>
                    {{ form_end(form_post) }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/main.js') }}"></script>
    <script src="{{ asset('js/bundles/ckeditor.js') }}"></script>
    <script>

        ClassicEditor
            .create(document.querySelector('#post_content'))
            .catch(error => {
                    console.error(error);
                }
            );
    </script>
{% endblock %}

templates/blog/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Панель автора{% endblock %}

{% block body %}
    <main>
        <div class="main">
            <h1 class="main-header c-t-black">ПАНЕЛЬ АВТОРА</h1>
            <div class="main-container">
                <nav class="container-nav">
                    <ul>
                        <li>
                            {% if app.user.firstName and app.user.lastName %}
                                <a href="{{ path('author.post_new') }}"><i class="fal fa-plus-square"></i> Новая статья</a>
                            {% else %}
                                <span>Чтобы добавлять новость. Зайдите в<a href="#"> настройки профиля</a> и заполните поля "Имя" и "Фамилия"</span>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
                <table>
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th class="t-w-400px">ЗАГОЛОВОК</th>
                        <th>ДАТА СОЗДАНИЯ</th>
                        <th>ДАТА РЕДАКТИРОВАНИЯ</th>
                        <th>META</th>
                        <th>СТАТУС</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if posts is empty %}
                        <tr>
                            <td class="table-is-empty" colspan="7">Empty</td>
                        </tr>
                    {% else %}
                        {% for post in posts %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td>{{ post.title }}</td>
                                <td>{{ post.createdAt|date('Y-m-d H:i') }}</td>
                                <td>{{ post.updatedAt|date('Y-m-d H:i') }}</td>
                                <td>
                                    <ul>
                                        <li class="badge c-bg-purple f-s-08">
                                            <span>{{ post.meta.views }} <i class="fal fa-eye"></i></span>
                                        </li>
                                        <li class="badge c-bg-purple f-s-08">
                                            <span>{{ post.meta.comments }} <i class="fal fa-comments-alt"></i></span>
                                        </li>
                                        <li class="badge c-bg-purple f-s-08">
                                            <span>{{ post.meta.likes }} <i class="fal fa-thumbs-up"></i></span>
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    {% if post.meta.status == 0 %}
                                        <span class="c-t-red f-s-08">НЕ АКТИВЕН</span>
                                    {% elseif post.meta.status == 1 %}
                                        <span class="c-t-turquoise f-s-08">АКТИВЕН</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <ul>
                                        <li class="badge c-bg-orange f-s-08">
                                            <a href="{{ path('author.post_edit', {id: post.id}) }}"><i class="fal fa-edit"></i> Edit</a>
                                        </li>
                                        <li class="badge c-bg-red f-s-08">
                                            {{ include('blog/author/_delete_form.html.twig', {post: post}, with_context = false) }}
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
{% endblock %}

templates/blog/author/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новая статья{% endblock %}

{% block body %}
    <main>
        <div class="main">
            <h1 class="main-header c-t-black">НОВАЯ СТАТЬЯ</h1>
            <div class="main-container">
                <div class="container-form width-700px align-hor-center">
                    {{ form_start(form_post) }}
                    <div class="form-error">{{ form_errors(form_post.title) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.title) }}
                        <div class="form-input">{{ form_widget(form_post.title) }}</div>
                    </div>

                    <div class="form-error">{{ form_errors(form_post.content) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.content) }}
                        {{ form_widget(form_post.content) }}
                    </div>

                    <div class="form-error">{{ form_errors(form_post.category) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.category) }}
                        {{ form_widget(form_post.category) }}
                    </div>

                    <div class="form-error">{{ form_errors(form_post.tags) }}</div>
                    <div class="form-control">
                        {{ form_label(form_post.tags) }}
                        {{ form_widget(form_post.tags)}}
                    </div>

                    <div class="form-control">
                        <div class="form-file">
                            <div class="field-file">{{ form_widget(form_post.img_path, {'attr': {'onchange': 'form_file_field(this);'}}) }}</div>
                            <label class="field-label" for="{{ form_post.img_path.vars.id }}"><i
                                        class="fal fa-upload"></i> Загрузить картинку</label>
                            <div class="field-file-name" id="form_file_name"></div>
                        </div>
                    </div>

                    <div class="form-control">
                        {{ form_widget(form_post.post) }}
                    </div>
                    {{ form_end(form_post) }}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/main.js') }}"></script>
    <script src="{{ asset('js/bundles/ckeditor.js') }}"></script>
    <script>

        ClassicEditor
            .create(document.querySelector('#post_content'))
            .catch(error => {
                    console.error(error);
                }
            );
    </script>
{% endblock %}